name: smallantimagmas
version: "0.2.8"
license: "GPL"
date: 2024-08-28
description: |
    A fork of smallgrp package for small antiassociative magmas

authors:
    - name: Kamil Zabielski

maintainers:
    - name: Kamil Zabielski

GAP: "4.12"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.5"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://limakzi.github.io/smallantimagmas
readme: README.md
packageinfo: https://limakzi.github.io/smallantimagmas/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/limakzi/smallantimagmas/releases/download/v0.2.8/smallantimagmas-v0.2.8.tar.gz

abstract: |
    The <span class="pkgname">smallantimagmas</span> package,    classifies all finite, antassociative magmas.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    smallantimagmas, antiassociative.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Zab24</span>]   <b class='BibAuthor'>Zabielski, K.</b>,
     <i class='BibTitle'>smallantimagmas, A fork of smallgrp package for small antiassociative magmas,
             Version 0.2.8</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://limakzi.github.io/smallantimagmas">https://limakzi.github.io/smallantimagmas</a></span>.
    </p>
    

bibtex: |
    @misc{ smallantimagmas,
      author =           {Zabielski, K.},
      title =            {{smallantimagmas},  A  fork  of  smallgrp  package for
                          small antiassociative magmas, {V}ersion 0.2.8},
      month =            {Aug},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href      {https://limakzi.github.io/smallantimagmas}
                          {\texttt{https://limakzi.github.io/}\discretionary
                          {}{}{}\texttt{smallantimagmas}}},
      keywords =         {smallantimagmas; antiassociative},
      printedkey =       {Zab24}
    }

